language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn global add codecov
  - yarn test
  - yarn codecov
  - yarn build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT
  on:
    branch: master